------------------------------
-- DROP TABLES
------------------------------
DROP TABLE Payment CASCADE CONSTRAINTS;
DROP TABLE Deduction CASCADE CONSTRAINTS;
DROP TABLE Payroll CASCADE CONSTRAINTS;
DROP TABLE Attendance CASCADE CONSTRAINTS;
DROP TABLE Employee CASCADE CONSTRAINTS;
DROP TABLE Position CASCADE CONSTRAINTS;
DROP TABLE Department CASCADE CONSTRAINTS;
